### ISSUE TITLE
Rasterio dependency issues

### ISSUE THREAD

**Issue by tobiashi26** [passaH2O/pygeoflood#15]
Hey,

I think the recent rasterio update from 1.3.11 to 1.4.1 caused some issues with the code (https://github.com/rasterio/rasterio/releases). I tried specifying a version in the requirements.txt and the pyproject.toml to 1.3.11, and it worked again. 

Here's the error:

Traceback (most recent call last):
  File "C:\pygeoflood_practice\Practice_Woodville\dockerfile_practice\main.py", line 4, in <module>
    woodville_test.pygeoflood_woodville()
  File "C:\pygeoflood_practice\Practice_Woodville\dockerfile_practice\app\woodville_test.py", line 36, in pygeoflood_woodville
    pgf.extract_channel_network()
  File "C:\Users\tobia\Miniconda3\envs\pygeoflood-env2\Lib\site-packages\pygeoflood\tools.py", line 101, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobia\Miniconda3\envs\pygeoflood-env2\Lib\site-packages\pygeoflood\tools.py", line 170, in wrapper
    return func(self, **final_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobia\Miniconda3\envs\pygeoflood-env2\Lib\site-packages\pygeoflood\pygeoflood.py", line 1619, in extract_channel_network
    channel_network, stream_rowcol, stream_keys = t.get_channel_network(
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobia\Miniconda3\envs\pygeoflood-env2\Lib\site-packages\pygeoflood\tools.py", line 1326, in get_channel_network
    indices, _ = route_through_array(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobia\Miniconda3\envs\pygeoflood-env2\Lib\site-packages\skimage\graph\mcp.py", line 88, in route_through_array
    return m.traceback(end), costs[end]
                             ~~~~~^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
ERROR conda.cli.main_run:execute(124): `conda run python main.py` failed. (See above for error)

**Comment by markwang0** [comment]
closed with #16
